name: Bug Report
description: Report bugs with the engine here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Terminal / Debug / Crash logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modtype
    attributes:
      label: "Where does this bug occur?"
      options:
        - "Source Code Modding"
        - "Modpack (HScript)"
        - "Modpack (Lua)"
    validations:
      required: true

  - type: dropdown
    id: buildtarget
    attributes:
      label: "What target are you using this engine with?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "HTML5 / Browser"
        - "Neko / HashLink"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything from source code? Summarize your changes."
      description: "You may ignore this question if you are not making a source code mod!"
      placeholder: "I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Put any additional notes about this bug here."
      description: "Anything that helps identify the cause of this bug faster should help!"
    validations:
      required: false