name: Feature Request
description: Request... a feature!
labels: [enhancement]
body:
  - type: textarea
    id: request
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true

  - type: dropdown
    id: requesttype
    attributes:
      label: "What does this feature request cover?"
      options:
        - "Internal (source code improvement)"
        - "HScript Scripting"
        - "Lua Scripting"
        - "Other"
    validations:
      required: true
  
  - type: textarea
    id: purpose
    attributes:
      label: How would users of the engine benefit from this feature?
    validations:
      required: true