name: Help Wanted
description: If you need help using the engine.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: modtype
    attributes:
      label: "Are you making a Source Code Modification, or a Modpack?"
      options:
        - Source Code Mod
        - Modpack
    validations:
      required: true

  - type: dropdown
    id: buildtarget
    attributes:
      label: "What target are you using?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "HTML5"
        - "Flash/Air-based target"
        - "Neko, HashLink, or other build system"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything from source code? Summarize your changes."
      description: "You may ignore this question if you are not making a source code mod!"
    validations:
      required: false
