name: Build

on:
  push:
    branches:
      - main
      - experimental
  pull_request:
    branches:
      - main
      - experimental
  workflow_dispatch:

jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore Build Cache
        uses: actions/cache@v6
        with:
          key: cacheLinux
          path: |
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
            cacheLinux

      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Create version tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Publish artifact
        uses: actions/upload-artifact@v7
        with:
          name: linuxBuild
          path: export/release/linux/bin

  buildWindows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore Build Cache
        uses: actions/cache@v6
        with:
          key: cacheWindows
          path: |
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cacheWindows

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/windows.bat"
        shell: cmd

      - name: Create version tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Publish artifact
        uses: actions/upload-artifact@v7
        with:
          name: windowsBuild
          path: export/release/windows/bin

  buildMac:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore Build Cache
        uses: actions/cache@v6
        with:
          key: cacheMac
          path: |
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cacheMac

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Create version tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Publish artifact
        uses: actions/upload-artifact@v7
        with:
          name: macBuild
          path: export/release/macos/bin
